### ISSUE TITLE
`mka recoveryimage` builds successfully without actually making a recovery.img file

### ISSUE THREAD

**Issue by alchimestre** [minimal-manifest-twrp/platform_manifest_twrp_aosp#5] opened 2021-10-03 01:46 UTC
See the title.

The build goes through fine but no actual recovery.img file is ever produced.
I'm honestly out of my depth here.

You can check the full Travis console log over [there](https://api.travis-ci.com/v3/job/540965764/log.txt).

Here's [soong.log](https://pastebin.com/S8E5DfbE).

My device tree with the .travis.yml build script are over [there](https://github.com/Vloupmon/TWRP_Realme_RMX3085).

**Comment by MartinX3** [comment] 2021-10-03 09:48
@Vloupmon where are your device tree parameters to activate recovery / or recovery inside boot?

**Comment by alchimestre** [comment] 2021-10-03 13:32
@MartinX3 I'm honestly not sure what you mean. I'm unfamiliar with Android and I'm mostly grokking this by relying on automated tools and other device trees to get a mild sense of what's going on. I went to check and I found that I was missing /vendor and /system dirs in /recovery/root that I thought were already there, and my BoardConfig.mk missed RECOVERY variables I also thought were also there. But I'm really not sure I've put the right stuff in. In any case it doesn't build any image.

Is there any explicit thing to toggle to "activate recovery" as you put it ?

As much as I'm trying to do it the right way, I've found there's an extreme lack of clear documentation on this. Most of it is outdated configuration files and how-to's spread out everywhere, copying each other without any explanation on what does what.

**Comment by MartinX3** [comment] 2021-10-03 13:46
@Vloupmon Yes, we lack documentation, sadly.
I also need to look at working device trees (and theor git history) and in the python/mk/bp code of aosp and its gerrit.

**Comment by MartinX3** [comment] 2021-10-05 09:22
I'm closing it since it should be caused by missing mk flags in your device tree.
Feel free to join our zulip server (readme) to ask for assistance. :)

**Closed as completed by MartinX3** 2021-10-05 09:22 UTC

**Comment by edward0181** [comment] 2022-03-27 15:22
There is no recoveryimage size in your boardconfig... will not make.

Please insert a correct size in boardconfig.mk

**Comment by sezanzeb** [comment] 2024-04-05 17:53
> I'm closing it since it should be caused by missing mk flags in your device tree.

@MartinX3 Do you know what the name of this flag is exactly?

**Comment by Goldenkrew3000** [comment] 2024-05-24 23:55
@sezanzeb Im 99% sure it is 'BOARD_RECOVERYIMAGE_PARTITION_SIZE', and it takes the size in bytes :)
